### ISSUE TITLE
受賞歴

### ISSUE THREAD

**Issue by gedorinku** [ProgrammingLab/prolab-accounts-client#38]
- [x] トップページに表示
- [x] 追加
- [x] 削除
- [x] 編集
- [x] メンバーの編集
- [x] 画像の追加
- [x] css

https://github.com/ProgrammingLab/prolab-accounts/issues/50

**Comment by mucho613** [comment]
[ログ] 3/13
受賞歴、活動実績が出るところを統一する感じにしようかなという話が出た
![SharedScreenshot](https://user-images.githubusercontent.com/7140505/54329449-0fa2c200-4655-11e9-8336-107b11c59c99.jpg)

**Comment by gedorinku** [comment]
@mucho613 
戦歴にメンバー一覧とURLも表示したい

**Comment by gedorinku** [comment]
<img width="800" alt="スクリーンショット 2019-04-11 18 38 41" src="https://user-images.githubusercontent.com/8470011/55947250-112dcd00-5c89-11e9-8936-f833e3c090a3.png">
2560x1600みたいな高解像度の環境だと左側がくっつかないのって正しい挙動?

**Comment by gedorinku** [comment]
想定してない挙動だとしてもほとんどの環境には影響がないから気にならないけど、一応
