### ISSUE TITLE
/member/:memberId ではなく /members/:memberIdの方が良さそう

### ISSUE THREAD

**Issue by gedorinku** [ProgrammingLab/prolab-accounts-client#82]
#81 で実装されたやつ。
https://github.com/ProgrammingLab/prolab-accounts-client/blob/45a8aa318deb4a751a240a6e80fcd0ceed3ed03a/src/router.js#L57

`/members/:memberId` の方が一般的っぽい。
https://cloud.google.com/apis/design/resource_names

CC: @kp54

**Comment by Fukusan64** [comment]
@gedorinku 
今はサーバーからプロフィールを持ってくるときにuser nameを使う関係で`/member/:name`になってるけど同じように`/members/:name`ってすればいいかな
僕が直しときます

**Comment by gedorinku** [comment]
```
今はサーバーからプロフィールを持ってくるときにuser nameを使う関係で/member/:nameになってるけど
```
これどういうこと?

**Comment by gedorinku** [comment]
#70 でそうなってるって意味か。わかる。

**Comment by Fukusan64** [comment]
多分合ってると思う
最初(kpが書いたとき)はmemberIdでどの部員かを指定するつもりだったけどあとでapiがuser nameでユーザーを指定してるのに気づいてページのリンクも`/member/:name`にしたって感じ
